ALTER TABLE users DROP COLUMN IF EXISTS password;
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS first_name VARCHAR (100) NOT NULL,
    ADD COLUMN IF NOT EXISTS last_name VARCHAR (100) NOT NULL,
    ADD COLUMN IF NOT EXISTS keycloak_id VARCHAR (255) UNIQUE NOT NULL;